var nameList = [
  "Henry Wilson",
  "Alexander Ortiz",
  "Jackson Smith",
  "Stella Morgan",
  "Sophia Jones",
  "Luna Gray",
  "Zoe Morgan",
  "Dylan Edwards",
  "Natalie King",
  "Charlotte Davis",
  "Zoe Lewis",
  "Zoey Ruiz",
  "Addison Nelson",
  "Charlotte Brooks",
  "Olivia Wright",
  "Zoey Phillips",
  "Scarlett Scott",
  "David Jackson",
  "Grace Kim",
  "Julian Harris",
  "Daniel Williams",
  "Penelope Watson",
  "Zoe Lewis",
  "Aurora Moore",
  "Abigail Anderson",
  "Olivia Cruz",
  "Mason Williams",
  "Camila Lee",
  "Amelia Morgan",
  "Ava Johnson",
  "Matthew Wood",
  "Andrew Miller",
  "Layla Garcia",
  "Olivia Mendoza",
  "Zoey Gonzalez",
  "Andrew Wilson",
  "Violet Ruiz",
  "Mila Turner",
  "Ethan Gutierrez",
  "Owen Hughes",
  "Layla Murphy",
  "Ava Taylor",
  "Addison Rodriguez",
  "James Flores",
  "Joseph Baker",
  "Wyatt Walker",
  "Nathan Jackson",
  "Madison Walker",
  "Scarlett Walker",
  "Addison Gutierrez",
  "Lily Nelson",
  "Isaac Brooks",
  "Hazel Young",
  "Ava Ramos",
  "Victoria James",
  "Ellie Reed",
  "Stella Moore",
  "Anna Howard",
  "Nova Green",
  "Daniel Reed",
  "James Gomez",
  "John Johnson",
  "Joshua Phillips",
  "Zoey Kelly",
  "Charlotte Gonzalez",
  "Wyatt Ward",
  "Jacob Gutierrez",
  "Mateo Wilson",
  "Stella Baker",
  "Carter Williams",
  "Emily Taylor",
  "Scarlett Roberts",
  "Anna Scott",
  "James Ramirez",
  "Ethan Thomas",
  "Harper Jackson",
  "Mateo Wood",
  "Jack King",
  "Dylan Johnson",
  "Nathan Bennett",
  "Nathan Mendoza",
  "Natalie Cook",
  "Emily Baker",
  "Sophia Phillips",
  "Charlotte Hill",
  "Wyatt Young",
  "Lillian Robinson",
  "Lincoln James",
  "Emma Cook",
  "Nova Evans",
  "Alexander Watson",
  "Samuel Smith",
  "Daniel Ramirez",
  "Levi Mitchell",
  "Mia Rogers",
  "Mila Stewart",
  "Aubrey White",
  "Isabella Hill",
  "Aiden Lee",
  "Sebastian Young",
];

export function getRandomNames() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

var commentList = [
  "What an unexpected turn!",
  "I'm really glad!",
  "This is incredible!",
  "This is crazy talk!",
  "This is remarkable!",
  "What a blast!",
  "I'm absolutely thrilled!",
  "What just happened?",
  "What a shocker!",
  "What a moment!",
  "What an unexpected turn!",
  "What a moment!",
  "What a surprise!",
  "What a great result!",
  "This is stunning!",
  "What a joy!",
  "This is extraordinary!",
  "What an incredible moment!",
  "Ain't no way!",
  "I'm at a loss for words!",
  "I'm really enthusiastic about this!",
  "What a wonderful surprise!",
  "I'm absolutely thrilled!",
  "I'm really eager for this!",
  "This is ridiculous!",
  "I'm delighted!",
  "This is wonderful!",
  "This is insane!",
  "Seriously, though?",
  "This is terrific!",
  "This is remarkable!",
  "I'm absolutely thrilled!",
  "What a plot twist!",
  "I'm flabbergasted!",
  "This is fabulous!",
  "This is excellent!",
  "This is too good to be true!",
  "Come on, really?",
  "What a blast!",
  "I can't handle this!",
  "I'm absolutely thrilled!",
  "What even?!",
  "This is terrific!",
  "This is superb!",
  "I can't even!",
  "What a thrill!",
  "This is fabulous!",
  "This is sensational!",
  "What a surprise!",
  "This is spectacular!",
  "What a delight!",
  "This is breathtaking!",
  "I'm really surprised!",
  "This is out of this world!",
  "I'm stunned!",
  "This is splendid!",
  "What a moment!",
  "I'm really happy about this!",
  "I'm really enthusiastic about this!",
  "I'm really looking forward to this!",
  "This is superb!",
  "What is bro yapping about?",
  "What a triumph!",
  "This is terrific!",
  "What even?!",
  "This is epic!",
  "What a shocker!",
  "This is marvelous!",
  "This can't be real!",
  "I'm really looking forward to this!",
  "I'm delighted!",
  "This is marvelous!",
  "I'm shocked!",
  "I'm truly amazed!",
  "I can't even!",
  "This is mind-blowing!",
  "I'm absolutely thrilled!",
  "This is spectacular!",
  "What is bro yapping about?",
  "I'm flabbergasted!",
  "This is stunning!",
  "I'm really eager for this!",
  "I'm really surprised!",
  "This is too good to be true!",
  "What a wonderful result!",
  "This is epic!",
  "What a pleasant surprise!",
  "I'm over the moon!",
  "This can't be real!",
  "I'm really surprised!",
  "What a plot twist!",
  "I'm really impressed!",
  "I'm delighted!",
  "Incredible!",
  "I'm shocked!",
  "What a great result!",
  "What a fantastic outcome!",
  "This is brilliant!",
  "What even?!",
  "Oh my gosh!",
];

export function getRandomComments() {
  return commentList[Math.floor(Math.random() * commentList.length)];
}
